In [3]:


import pandas as pd
import numpy as np
from IPython.display import display

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# Load Iris dataset (built into scikit-learn, no upload needed)
iris = load_iris()

data = pd.DataFrame(
    iris.data,
    columns=[
        "SepalLengthCm",
        "SepalWidthCm",
        "PetalLengthCm",
        "PetalWidthCm"
    ]
)

# Add target column
data["Species"] = [
    iris.target_names[i] for i in iris.target
]

print("First five records:")
display(data.head())

print("Dataset Shape:", data.shape, "-> 4 input features + 1 target column")

print("\nDataset Information:")
data.info()

print("\nClass distribution:")
print(data["Species"].value_counts())


# Separate the 4 input features from the target column
feature_cols = [
    "SepalLengthCm",
    "SepalWidthCm",
    "PetalLengthCm",
    "PetalWidthCm"
]

X = data[feature_cols]
y = data["Species"]


# Encode target labels into numbers
encoder = LabelEncoder()
y = encoder.fit_transform(y)


# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# Standardize the input features
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# MLPClassifier trains the neural network using error backpropagation
model = MLPClassifier(
    hidden_layer_sizes=(10,),
    activation="relu",
    solver="sgd",
    learning_rate_init=0.01,
    max_iter=1000,
    random_state=42
)


# Train the model
model.fit(X_train, y_train)


# Predict test data
y_pred = model.predict(X_test)


# Display actual and predicted values
print("\nActual Values:")
print(y_test)

print("\nPredicted Values:")
print(y_pred)


# Accuracy
print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))


# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


# Classification Report
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=encoder.classes_,
        zero_division=0
    )
)


# Predict a new sample
# Same 4 features and same order
new_sample = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=feature_cols
)

# Scale the new sample
new_sample_scaled = scaler.transform(new_sample)

# Make prediction
prediction = model.predict(new_sample_scaled)

# Convert numeric prediction back to species name
print(
    "\nNew Sample Prediction:",
    encoder.inverse_transform(prediction)[0]
)

First five records:


,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


Dataset Shape: (150, 5) -> 4 input features + 1 target column

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    str    
dtypes: float64(4), str(1)
memory usage: 6.0 KB

Class distribution:
Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

Actual Values:
[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 1 1 0 2 0]

Predicted Values:
[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]

Accuracy:
0.9666666666666667

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00    

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Species  
0        0  
1        0  
2        0  
3        0  
4        0  
