In [1]:
# Save the notebook as: Naivebayes_classifier.ipynb

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# Create Play Tennis dataset
data = pd.DataFrame({
    "Outlook": [
        "Sunny", "Sunny", "Overcast", "Rain", "Rain",
        "Rain", "Overcast", "Sunny", "Sunny", "Rain",
        "Sunny", "Overcast", "Overcast", "Rain"
    ],
    "Temperature": [
        "Hot", "Hot", "Hot", "Mild", "Cool",
        "Cool", "Cool", "Mild", "Cool", "Mild",
        "Mild", "Mild", "Hot", "Mild"
    ],
    "Humidity": [
        "High", "High", "High", "High", "Normal",
        "Normal", "Normal", "High", "Normal", "Normal",
        "Normal", "High", "Normal", "High"
    ],
    "Wind": [
        "Weak", "Strong", "Weak", "Weak", "Weak",
        "Strong", "Strong", "Weak", "Weak", "Weak",
        "Strong", "Strong", "Weak", "Strong"
    ],
    "Play": [
        "No", "No", "Yes", "Yes", "Yes",
        "No", "Yes", "No", "Yes", "Yes",
        "Yes", "Yes", "Yes", "No"
    ]
})


print("First five records:")
display(data.head())

print("Dataset Shape:", data.shape)

print("\nClass distribution:")
print(data["Play"].value_counts())


# Encode each categorical column
encoded_data = data.copy()

encoders = {}

for column in encoded_data.columns:
    encoders[column] = LabelEncoder()
    encoded_data[column] = encoders[column].fit_transform(
        encoded_data[column]
    )


# Separate input features and target
X = encoded_data.drop("Play", axis=1)
y = encoded_data["Play"]


# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)


# Create Gaussian Naive Bayes model
model = GaussianNB()


# Train the model
model.fit(X_train, y_train)


# Predict test data
y_pred = model.predict(X_test)


# Display actual and predicted values
print("\nActual Values:")
print(y_test.to_numpy())

print("\nPredicted Values:")
print(y_pred)


# Calculate accuracy
print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))


# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


# Classification Report
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)


# Predict a new sample
# Outlook = Sunny
# Temperature = Cool
# Humidity = Normal
# Wind = Weak

new_sample = pd.DataFrame(
    [["Sunny", "Cool", "Normal", "Weak"]],
    columns=["Outlook", "Temperature", "Humidity", "Wind"]
)


# Encode new sample using the same encoders
for column in new_sample.columns:
    new_sample[column] = encoders[column].transform(
        new_sample[column]
    )


# Predict the new sample
prediction = model.predict(new_sample)


# Convert prediction back to Yes/No
predicted_class = encoders["Play"].inverse_transform(
    prediction
)[0]


print("\nNew Sample Prediction:", predicted_class)

First five records:


,Outlook,Temperature,Humidity,Wind,Play
0,Sunny,Hot,High,Weak,No
1,Sunny,Hot,High,Strong,No
2,Overcast,Hot,High,Weak,Yes
3,Rain,Mild,High,Weak,Yes
4,Rain,Cool,Normal,Weak,Yes


Dataset Shape: (14, 5)

Class distribution:
Play
Yes    9
No     5
Name: count, dtype: int64

Actual Values:
[1 1 0 1 0]

Predicted Values:
[1 0 0 1 1]

Accuracy:
0.6

Confusion Matrix:
[[1 1]
 [1 2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.67      0.67      0.67         3

    accuracy                           0.60         5
   macro avg       0.58      0.58      0.58         5
weighted avg       0.60      0.60      0.60         5


New Sample Prediction: Yes
